// SyncPoint mock data
// All in one place; components read from window.SP_DATA.

const LAUNCHES = [
  {
    id: "lnch-atlas",
    code: "L-204",
    name: "Atlas — Multi-region failover",
    pillar: "Infra",
    owner: { pm: "Priya Shah", pmm: "Marcus Lee", eng: "Diego Alvarez" },
    target: "May 19",
    daysToShip: 13,
    risk: "yellow",
    readiness: 72,
    eng: 88,
    gtm: 56,
    env: "Staging",
    freeze: "May 14",
    pinned: true,
    delta: +6,
    blockers: 1,
    summary: [
      "Customers can configure automatic failover between US-East and EU-West with sub-90s RTO.",
      "Removes the manual escalation step that the support team currently runs during outages.",
      "Enterprise tier only — surfaces a new ‘Failover’ tab inside the Reliability dashboard.",
      "Pricing page gets a new comparison row; sales decks need an updated SLA slide.",
      "No public API changes; SDKs unaffected this release."
    ],
    assets: [
      { id: 1, kind: "Screenshot", title: "Failover dashboard — empty state", source: "src/reliability/Failover.tsx", status: "ready" },
      { id: 2, kind: "Screenshot", title: "Region switcher — active", source: "src/reliability/RegionPicker.tsx", status: "ready" },
      { id: 3, kind: "Loom", title: "End-to-end failover walkthrough (90s)", source: "src/reliability/*", status: "draft" },
      { id: 4, kind: "Screenshot", title: "Audit log — failover event row", source: "src/audit/EventRow.tsx", status: "blocked" },
      { id: 5, kind: "Hero image", title: "Marketing hero — globe with two pins", source: "design", status: "todo" },
    ],
    tickets: [
      { id: "ENG-2241", title: "Region health probe — exponential backoff", state: "Done", env: "Production" },
      { id: "ENG-2244", title: "Failover state machine — write path", state: "Done", env: "Canary" },
      { id: "ENG-2247", title: "Audit log — failover event type", state: "In review", env: "Staging" },
      { id: "ENG-2251", title: "Settings UI — region picker", state: "In progress", env: "Local" },
      { id: "ENG-2258", title: "Docs — runbook update", state: "To do", env: "—" },
    ],
    deps: [
      { id: "d1", label: "Legal review — SLA language", status: "done", owner: "Legal", hard: true },
      { id: "d2", label: "QA verification — chaos test pass", status: "in-progress", owner: "QA", hard: true },
      { id: "d3", label: "Pricing page update", status: "in-progress", owner: "Web", hard: false },
      { id: "d4", label: "Sales enablement deck", status: "blocked", owner: "PMM", hard: true },
      { id: "d5", label: "Support runbook", status: "todo", owner: "Support", hard: false },
    ],
    activity: [
      { t: "12 min ago", who: "Diego A.", what: "merged ENG-2244 → Canary" },
      { t: "1h ago", who: "AI Bridge", what: "drafted asset list from commit a7f2c1" },
      { t: "3h ago", who: "Priya S.", what: "set freeze date to May 14" },
      { t: "Yesterday", who: "Marcus L.", what: "uploaded hero image v3" },
    ],
  },
  {
    id: "lnch-glide",
    code: "L-198",
    name: "Glide — AI-assisted onboarding",
    pillar: "Growth",
    owner: { pm: "Tomás Rivera", pmm: "Ana Park", eng: "Yuki Tanaka" },
    target: "May 12",
    daysToShip: 6,
    risk: "red",
    readiness: 41,
    eng: 62,
    gtm: 24,
    env: "Staging",
    freeze: "May 9",
    delta: -8,
    blockers: 3,
    summary: [
      "First-run flow now uses a 3-question intent picker instead of a 9-step tour.",
      "AI-suggested workspace template based on the user’s answers; dismissible.",
      "Drops time-to-first-value from 11 minutes to 3 minutes in internal tests.",
      "Marketing launch tied to the Q2 self-serve push.",
    ],
    assets: [],
    tickets: [],
    deps: [],
    activity: [],
  },
  {
    id: "lnch-marble",
    code: "L-211",
    name: "Marble — Audit log v2",
    pillar: "Compliance",
    owner: { pm: "Hana Cho", pmm: "Wes Patel", eng: "Sam Okafor" },
    target: "Jun 02",
    daysToShip: 27,
    risk: "green",
    readiness: 84,
    eng: 91,
    gtm: 77,
    env: "Production",
    freeze: "May 28",
    delta: +2,
    blockers: 0,
    summary: [],
    assets: [],
    tickets: [],
    deps: [],
    activity: [],
  },
  {
    id: "lnch-orbit",
    code: "L-218",
    name: "Orbit — Workspace templates",
    pillar: "Growth",
    owner: { pm: "Lior Ben", pmm: "Ana Park", eng: "Mei Wong" },
    target: "Jun 16",
    daysToShip: 41,
    risk: "green",
    readiness: 38,
    eng: 44,
    gtm: 31,
    env: "Local",
    freeze: "Jun 11",
    delta: +12,
    blockers: 0,
    summary: [],
    assets: [],
    tickets: [],
    deps: [],
    activity: [],
  },
  {
    id: "lnch-nimbus",
    code: "L-221",
    name: "Nimbus — SSO for SCIM groups",
    pillar: "Platform",
    owner: { pm: "Priya Shah", pmm: "Wes Patel", eng: "Diego Alvarez" },
    target: "May 26",
    daysToShip: 20,
    risk: "yellow",
    readiness: 58,
    eng: 71,
    gtm: 44,
    env: "Canary",
    freeze: "May 21",
    delta: 0,
    blockers: 1,
    summary: [],
    assets: [],
    tickets: [],
    deps: [],
    activity: [],
  },
  {
    id: "lnch-pebble",
    code: "L-225",
    name: "Pebble — Mobile widget gallery",
    pillar: "Mobile",
    owner: { pm: "Hana Cho", pmm: "Marcus Lee", eng: "Yuki Tanaka" },
    target: "Jun 23",
    daysToShip: 48,
    risk: "green",
    readiness: 22,
    eng: 28,
    gtm: 17,
    env: "Local",
    freeze: "Jun 18",
    delta: +4,
    blockers: 0,
    summary: [],
    assets: [],
    tickets: [],
    deps: [],
    activity: [],
  },
];

const NAV = [
  { id: "home", label: "Launches", icon: "rocket" },
  { id: "timeline", label: "Timeline", icon: "timeline" },
  { id: "bridge", label: "AI Bridge", icon: "bridge", badge: 3 },
  { id: "deps", label: "Dependencies", icon: "deps" },
  { id: "feed", label: "Activity", icon: "feed" },
];

const PILLARS = ["All", "Infra", "Growth", "Platform", "Compliance", "Mobile"];

window.SP_DATA = { LAUNCHES, NAV, PILLARS };
